# Generated by Django 2.2.6 on 2019-10-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190924_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
