# Generated by Django 2.2.5 on 2019-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, unpack_ipv4=True, verbose_name='IP地址')),
                ('first_time', models.DateTimeField(auto_now_add=True, verbose_name='首次访问时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('count', models.IntegerField(default=1, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '访问者',
                'verbose_name_plural': '访问者',
            },
        ),
    ]
