# Generated by Django 2.2.6 on 2019-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='鸡汤')),
                ('hits', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '毒鸡汤',
                'verbose_name_plural': '毒鸡汤',
            },
        ),
    ]
