# Generated by Django 2.2.6 on 2019-10-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_soul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soul',
            name='title',
            field=models.TextField(max_length=300, verbose_name='鸡汤'),
        ),
    ]
